# Generated by Django 3.0.8 on 2020-11-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=25)),
            ],
        ),
    ]
