# Generated by Django 3.0.8 on 2020-11-23 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('birthday', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default=None, max_length=25)),
                ('subject', models.CharField(choices=[('Physics', 'PHYSICS'), ('Chemistry', 'CHEMISTRY'), ('Maths', 'MATHS')], default=None, max_length=25)),
                ('res_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=25, null=True)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
